#!/bin/bash

# The default style is hard to read when your terminal has blue
# suppressed, so a) assume 256 color terminal (instead of 8), and b)
# use "emacs" style rather than "colorful"
#PYG_FLAGS="-f 256 -O style=emacs"
#PYG_FLAGS="-O style=emacs"
# I'm liking this more minimal rrt style.
PYG_FLAGS="-f 256 -O style=rrt"

case "$1" in
    *.awk|*.groff|*.java|*.js|*.m4|*.php|*.pl|*.pm|*.pod|*.sh|\
    *.ad[asb]|*.asm|*.inc|*.[ch]|*.[ch]pp|*.[ch]xx|*.cc|*.hh|\
    *.lsp|*.l|*.pas|*.p|*.xml|*.xps|*.xsl|*.axp|*.ppd|*.pov|\
    *.diff|*.patch|*.py|*.rb|*.sql|*.ebuild|*.eclass|*.el)
        pygmentize ${PYG_FLAGS} "$1";;
    .bashrc|.bash_aliases|.bash_environment|aliases)
        pygmentize ${PYG_FLAGS} -l sh "$1"
        ;;
    *.ino)
	pygmentize ${PYG_FLAGS} -l c++ "$1"
	;;
    Makefile|*.mk|*.mf)
        pygmentize ${PYG_FLAGS} -l make "$1"
        ;;
    *)
        grep "#\!/bin/bash" "$1" > /dev/null
        if [ "$?" -eq "0" ]; then
            pygmentize ${PYG_FLAGS} -l sh "$1"
        else
            exit 1
        fi
esac

exit 0
