#cathode
#gentrix
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/arjen-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/billw-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/simple-1-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/calm-forest-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/goldenrod-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/clarity-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/comidia-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/jsc-dark-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/dark-green-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/dark-laptop-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/euphoria-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/hober-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/late-night-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/lawrence-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/lethe-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/ld-dark-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/matrix-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/midnight-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/oswald-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/renegade-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/retro-green-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/retro-orange-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/salmon-font-lock-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/subtle-hacker-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/taming-mr-arneson-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/taylor-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/tty-dark-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/pok-wob-theme.el
curl -LO https://raw.githubusercontent.com/emacs-jp/replace-colorthemes/master/word-perfect-theme.el
