- name: gather debug info
  hosts: linux
  gather_facts: false

  tasks:
    - name: Gather recent vmstat info
      command: vmstat 1 5
      register: vmstat

    - name: Gather top CPU hogs
      command: ps -eo user,pid,size,pcpu,cmd --sort=-pcpu
      register: pscpu

    - name: Gather top memory hogs
      command: ps -eo user,pid,size,pcpu,cmd --sort=-size
      register: pssize

    - name: Swap + wait states
      debug:
        var: vmstat.stdout_lines

    - name: Top 3 CPU hogs
      debug:
        var: pscpu.stdout_lines[:4]

    - name: Top 3 memory hogs
      debug:
        var: pssize.stdout_lines[:4]
