- name: Remove Ubuntu Junk
  hosts: z
    # roles:
    #   - role: ironicbadger.ansible_role_bash_aliases
    #   - role: grog.package
    #   - role: geerlingguy.security
    #   - role: weareinteractive.environment
    #   - role: geerlingguy.ntp
    tasks:
      - name: remove ubuntu motd spam
        become: true
        file:
          path: "/etc/update-motd.d/{{ item }}"
          state: absent
        loop:
          - 80-livepatch
          - 95-hwe-eol
          - 10-help-text
          - 50-motd-news
        when: ansible_distribution == 'Ubuntu'
