- name: Update my dotfiles everywhere
  hosts: linux

  tasks:

  - name: Fetch my stuff
    shell: cd myDotfiles && GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_github" git pull
    register: pull_result
    changed_when: pull_result.stdout is not search('Already up to date.')

#  - debug:
#      var: pull_result
